# bd/compose.yml
services:
  mariadb:
    build: .
    container_name: mariadb_local
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: jobmatch
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
